[target.thumbv7m-none-eabi]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = './debug.sh'

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
]

[build]
target = "thumbv7em-none-eabi"
